### PR TITLE
Upload website codes

### PR DESCRIPTION
**Pull request by athityakumar**

### CODE REVIEW

**Comment by dkuntal** [comment]
1. Blog in different page. Like "vriitkgp.github.io/blog"
2. Meet us : iitkgp address
3. Competitions :
   https://vrjam.devpost.com/
   https://developer.leapmotion.com/3djam
   http://www.ntefund.am/en/our-projects/show/17
   https://connect.innovateuk.org/web/virtual-and-augmented-reality-innovation-contest

Peace?

**Comment by rustybuddha** [comment]
blogging through github pages, yup! let's do that for blogging. Ok

**Comment by dkuntal** [comment]
For OUR TEAM part :
Will it be ok if you make every person's details in [this](http://krssg.in/portfolio.html) format.
I think if you put facebook, linkedin, g+ link, it will look more informative.

@Calibre720 what do you say?

**Comment by rustybuddha** [comment]
leave me out of this part. I have problems sharing my real life identity online, so no photo, and no info.
yeah I will go ahead with the rest.

**Comment by dkuntal** [comment]
At least name?

**Comment by rustybuddha** [comment]
but then that wouldn't fit-in with everyone else's information templates

**Comment by dkuntal** [comment]
Peace. If he links to your facebook profile picture, will that be alright?

**Comment by rustybuddha** [comment]
Haha, use the github one

**Comment by dkuntal** [comment]
Ye sab jo bhi tera decision h, please send these to ati as an email

**Comment by rustybuddha** [comment]
Dude, remove that alpari.com contest, it is a trading contest

**Comment by dkuntal** [comment]
I see
which link?

**Comment by rustybuddha** [comment]
oh sorry, remove this one https://connect.innovateuk.org/web/virtual-and-augmented-reality-innovation-contest

**Comment by rustybuddha** [comment]
It is only for UK or EU sponsored by InnovateUK, that can't even be in our list of possible contests

**Comment by rustybuddha** [comment]
Ye wala bhi peace maar -  http://www.ntefund.am/en/our-projects/show/17 
it's only for Armenia, some country, the application form is not even in English

Only LeamMotion and VRJam

**Comment by dkuntal** [comment]
Then final request
1. Blog in different page. Like "vriitkgp.github.io/blog"
2. Meet us : iitkgp address
3. Competitions :
   https://vrjam.devpost.com/
   https://developer.leapmotion.com/3djam
   http://www.ntefund.am/en/our-projects/show/17
4. OUR TEAM format as described before

**Comment by rustybuddha** [comment]
Only LeamMotion and VRJam

**Comment by dkuntal** [comment]
Fine. Ati now it's all your work left

**Comment by athityakumar** [comment]
Added with PR #2. Neglect this PR.

**Pull request closed without merging**
